### ISSUE TITLE
option : automatic node width set to match widest sibling

### ISSUE THREAD

**Issue by kenfhill84083** [freeplane/freeplane#1157]
**Feature Request**
It would help me if FP had an **option** to automatically resize sibling nodes to match the widest of the siblings.

**Is your feature request related to a problem? Please describe.**
I often want sibling nodes to be equal width.  But usually I have to manually resize after all the siblings have been created.  And then if I add an icon to one or change font size, etc, I again have to manually resize.

Selecting the siblings and resizing with alt+mousewheel is handy but it still can be tedious.

**priority**
I don't see this as an extremely high priority.  But it would be useful for me.

**Comment by Bricklam** [comment]
there is a script that do what you want in the scripts collection to (unify the size for all the sibling nodes),
you can assign any keyboard shortcut to trigger it:
https://docs.freeplane.org/scripting/Scripts_collection.html#toggle-block-view-for-all-siblings

**Comment by kenfhill84083** [comment]
> there is a script that do what you want in the scripts collection to (unify the size for all the sibling nodes), you can assign any keyboard shortcut to trigger it: https://docs.freeplane.org/scripting/Scripts_collection.html#toggle-block-view-for-all-siblings

Thanks.  I get an error when I run it.  I did not change any of the configuration variables.  I wasn't sure what the 1st one was or what should go in it.  I don't have any special characters at the beginning of nodes.  I just have straight text like I'd have in any node.

The comments on all the configuration variables were a bit cryptic for me to understand.  I am not a coder by any stretch of the imagination.

Is this designed to automatically update every time I add a sibling or do I have to execute the script?  Automation is what I am looking for in this feature request.  I just want to add a node and have all siblings match the width of the widest sibling.

![equal width siblings _ error](https://github.com/freeplane/freeplane/assets/6380301/8c1c3e1e-8b82-416e-9db8-da09ec9e044a)

**Comment by kenfhill84083** [comment]
> there is a script that do what you want in the scripts collection to (unify the size for all the sibling nodes), you can assign any keyboard shortcut to trigger it: https://docs.freeplane.org/scripting/Scripts_collection.html#toggle-block-view-for-all-siblings

I suspect I can manually get the result I want just by using the built-in feature of alt-mouseWheel.  It is a bit tedious to select the group of siblings.  I may be too ignorant for this script.

**Comment by Bricklam** [comment]
OK. I tested the script and it worked for me without any errors.
it is not automatic. it you have to trigger it every time you want to set the siblings width to be equal to the one with the maximum width.
it is not that difficult, you can easily assign a keyboard shortcut, in my case I use (Ctrl+Shift+Z), to run it quickly.

I don't know why it doesn't work in your case. (maybe you didn't copy all the text or copied extra text)
 anyway I will upload my copy for you to test it. let me know if it works:
[toggle_block_view_for_all_siblings.zip](https://github.com/freeplane/freeplane/files/11526726/toggle_block_view_for_all_siblings.zip)

**Comment by kenfhill84083** [comment]
Thanks.  No errors.  But it did not work as I want, although it could have some use for me otherwise.  see video.

[script not working.zip](https://github.com/freeplane/freeplane/files/11531297/script.not.working.zip)

**Comment by kenfhill84083** [comment]
> OK. I tested the script and it worked for me without any errors. it is not automatic. it you have to trigger it every time you want to set the siblings width to be equal to the one with the maximum width. it is not that difficult, you can easily assign a keyboard shortcut, in my case I use (Ctrl+Shift+Z), to run it quickly.
> 
> I don't know why it doesn't work in your case. (maybe you didn't copy all the text or copied extra text) anyway I will upload my copy for you to test it. let me know if it works: [toggle_block_view_for_all_siblings.zip](https://github.com/freeplane/freeplane/files/11526726/toggle_block_view_for_all_siblings.zip)

Here is the map I tried it on

[What-Smart-Students-Know.zip](https://github.com/freeplane/freeplane/files/11531312/What-Smart-Students-Know.zip)

**Comment by Bricklam** [comment]
I checked your map and the script. and I think I found out why the script didn't work:
because you have changed the (Min node width) value for the default  style. you can check that by opening:
the style editing window (Format > Manage Styles > Edit styles),  you can see that the (Min node width) value is set to (11),
 which you shouldn't do here (in the style editing window), in order to make the script works.
So, you only need to set the Min node width value to 0, and then test the script again:

please let me know if this solves the problem:
![image2](https://github.com/freeplane/freeplane/assets/129968602/34e2e404-0493-4e26-8bf8-518c49fda246)
- this after re-setting the (Min node width) to the default value (should solve the problem)
![image4](https://github.com/freeplane/freeplane/assets/129968602/8ecb5596-2c80-426a-9769-0ea29a36a658)

**Comment by kenfhill84083** [comment]
>set the Min node width value to 0, and then test the script again

Works now.  I assume I will have to change my templates to the 0-width min node width?

Did you code this script?  I'm wondering what I could change so that if the current node was being edited the script would go ahead and complete the edit (like pressing Enter) and then do the width magic.  That would accomplish what my feature request is.

I'm still not sure what the configuration variables are for.  Have you ever had to change them?  If so, why?

**Comment by kenfhill84083** [comment]
Another little glitch - which I did not specifically ask for in my feature request - is that if the longest sibling has an icon, the script does not seem to take that into account.

That makes things look awkward.

![sibling width script with icons](https://github.com/freeplane/freeplane/assets/6380301/64145c24-498a-47a7-89cd-cbefcdf8e540)

**Comment by kenfhill84083** [comment]
> **Feature Request** It would help me if FP had an **option** to automatically resize sibling nodes to match the widest of the siblings.

It would be best if the feature took into account icons in any of the siblings, insuring that those with icons do not wrap text.

**Comment by kenfhill84083** [comment]
> then test the script again
>
I ran into a glitch when I downloaded a sample map from the Freemind [map repository](https://freemind.sourceforge.net/wiki/extensions/freemind/flashwindow.php?initLoadFile=/wiki/images/6/6e/Cool_Tools.mm&startCollapsedToLevel=5&mm_title=Cool_Tools.mm) on sourceforge (see zip file).

It eventually widens all siblings but it takes several runs of the script to finally do it.

[Cool_Tools.zip](https://github.com/freeplane/freeplane/files/11536286/Cool_Tools.zip)

**Comment by Bricklam** [comment]
yes. I tested the script on nodes with icons and it worked (took icons into consideration).
it may need to be executed after every editing process (to get the final width into consideration)

the script is not perfect but it is the best available way to set the width of all sibling nodes.

by the way I didn't edit or change any variable or parameters, I just copied the raw script into file, from this page:
https://docs.freeplane.org/scripting/Scripts_collection.html#toggle-block-view-for-all-siblings

I suggest to assign a keyboard shortcut to the script, in order to execute it quickly and effectively (multiple times if needed)
with keyboard shortcut: you can execute it even during inline-editing of a node.

to assign a keyboard shortcut: tools > scripts > put the mouse over the target script file and press (Ctrl),
then you can assign any keyboard shortcut for the script, which will make it very fast

**Comment by kenfhill84083** [comment]
Thanks. I am using it and have assigned a hotkey.

Every once in a while there will be a glitch and I have to select all the
siblings and resize with alt+mouseWheel.

Overall, very useful.

**Comment by kenfhill84083** [comment]
Thanks @Bricklam.

I am using it and have assigned a hotkey.

Every once in a while there will be a glitch and I have to select all the siblings and resize with alt+mouseWheel.

Overall, very useful.

I'm still hoping for a built-in version.  

I have had problems in the past losing script files and breaking my FP functionality - mostly with new hard drives.  I've tried securing this one on onedrive and dropbox.

**Comment by kenfhill84083** [comment]
> Overall, very useful.
> 

I am happy enough with this that I'm going to close this out even though I have run into little glitches and it is not what I asked for.  In some ways it is handier.
